---
- name: Load required variables based on the OS type
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"
  tags:
    - always

- name: Execute OS specific tasks
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "setup-{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "setup-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
    - "setup-{{ ansible_distribution|lower }}.yml"
    - "setup-{{ ansible_os_family|lower }}.yml"

- name: Include configure target tasks
  ansible.builtin.include_tasks:
    file: configure-target.yml
  with_items:
    - "{{ iscsi_targets }}"
  loop_control:
    loop_var: "target"

- name: Ensure targetcli configuration is loaded at boot
  ansible.builtin.service:
    name: "{{ iscsi_target_service_name }}"
    state: started
    enabled: true
