---
iscsi_targets:
  - name: "iqn.2021-11.blog.tauceti:{{ ansible_facts['nodename'] }}"
    disks:
      - name: lun_node1
        path: /dev/vdb
        type: block
        lunid: 0
    initiators:
      - name: iqn.2021-07.blog.tauceti:node1
        authentication:
          userid: node1user
          password: node1pw
          userid_mutual: node1sharedkey
          password_mutual: node1sharedsecret
        mapped_luns:
          - mapped_lunid: 0
            lunid: 0
    portals:
      - ip: "0.0.0.0"
