---
- name: Converge
  hosts: all
  remote_user: vagrant
  become: true
  gather_facts: true
  collections:
    - kewlfft.aur

- hosts: archlinux
  vars_files:
    - vars/archlinux.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include iscsi_target role
      include_role:
        name: githubixx.iscsi_target

- hosts: ubuntu2004
  vars_files:
    - vars/ubuntu.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include iscsi_target role
      include_role:
        name: githubixx.iscsi_target

- hosts: ubuntu1804
  vars_files:
    - vars/ubuntu.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include iscsi_target role
      include_role:
        name: githubixx.iscsi_target
