---
dependency:
  name: galaxy
  options:
    role-file: req.yml
    requirements-file: req.yml

lint: |
  set -e
  yamllint .
  ansible-lint

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ubuntu2004
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :size => '1G', :device => 'vdb'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.10
    groups:
      - ubuntu
  - name: archlinux
    box: archlinux/archlinux
    memory: 2048
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :size => '1G', :device => 'vdb'"
      - "storage :file, :size => '1G', :device => 'vdc'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.20
    groups:
      - archlinux
  - name: ubuntu2204
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :size => '1G', :device => 'vdb'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.30
    groups:
      - ubuntu

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible
