---
- name: Prepare
  hosts: archlinux
  gather_facts: false
  become: true
  tasks:
    - name: Init pacman
      raw: |
        pacman-key --init
        pacman-key --populate archlinux

    - name: Updating pacman cache
      raw: pacman -Sy

    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (pacman --noconfirm python)

    - name: Upgrade the whole system
      raw: pacman --noconfirm -Su

    - name: Reboot for kernel updates
      reboot:

- hosts: ubuntu
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
