---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'githubixx.iscsi_target'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'githubixx.iscsi_target'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: |
          repo_owner=$(echo "${{ github.repository }}" | cut -d/ -f1)
          repo_name=$(echo "${{ github.repository }}" | cut -d/ -f2)
          role_name=$(echo "$repo_name" | sed 's/ansible-role-//' | sed 's/-/_/')

          ansible-galaxy role import \
            --token "${{ secrets.GALAXY_API_KEY }}" \
            -vvv \
            --role-name="$role_name" \
            "$repo_owner" \
            "$repo_name"
